name: Continuous Integration

on: [push]

jobs:

  dist:
    name: Make distribution using Dist::Inkt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Perl Version
        run: |
          perl -V
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install Dist::Inkt
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n Dist::Inkt::Profile::TOBYINK
      - name: Make distribution
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          ~/perl5/bin/distinkt-dist --TRAVIS --targetdir=build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build

  test:
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    needs: dist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        perl: [ '5.8', '5.30' ]
    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Configure
        working-directory: ./build
        run: perl Makefile.PL
      - name: Install dependencies
        working-directory: ./build
        run: cpanm --installdeps .
      - name: Make
        working-directory: ./build
        run: make
      - name: Test
        working-directory: ./build
        run: |
          prove -b -r "t"